{{- if .Values.server.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apptracker.fullname" . }}-server
  labels:
    {{- include "apptracker.server.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.server.secrets.jwtSecret | b64enc | quote }}
{{- end }}
