# App Tracker Services
---
apiVersion: v1
kind: Service
metadata:
  name: apptracker-server
  namespace: apptracker
  labels:
    app.kubernetes.io/name: apptracker
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 32400
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: apptracker
    app.kubernetes.io/component: server

---
apiVersion: v1
kind: Service
metadata:
  name: apptracker-ui
  namespace: apptracker
  labels:
    app.kubernetes.io/name: apptracker
    app.kubernetes.io/component: ui
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: apptracker
    app.kubernetes.io/component: ui
